### ISSUE TITLE
[ci] Add macOS and windows to R-cmd-check workflow

### ISSUE THREAD

**Issue by maelle** [ropensci/GLMMcosinor#20]
To ensure things are not failing on Ubuntu only. 

Why not use https://github.com/r-lib/actions/blob/v2-branch/examples/check-standard.yaml? (`usethis::use_github_action("check-standard")` would download it for you)

**Comment by RWParsons** [comment]
Thanks for the suggestion @maelle - now that I'm not having so many issues with GHA, I've added it dev 0e62f6ff6cd7e08610b304126d0ef23648f26e06
