### ISSUE TITLE
Interpretation of the polar plot.

### ISSUE THREAD

**Issue by MilaSMayor** [ropensci/GLMMcosinor#25]
Dear GLMMcosinor developer,

Following the reference Cornelissen, Germaine. 2014. “Cosinor-Based Rhythmometry.” Theoretical Biology and Medical Modelling 11 (1): 1–24. I would like to know if the interpretation of polar plot is as the one explained in the article. Namely, the figure 2 explains in the caption this:

This is illustrated by the elliptical 95% confidence region for the amplitude-acrophase pair (bottom). When the error ellipse does not cover the pole, the zero-amplitude (no-rhythm) test is rejected and the alternative hypothesis holds that a rhythm with the given period is present in the data (left). Conservative 95% confidence limits for the amplitude and acrophase can then be obtained by drawing concentric circles and radii tangent to the error ellipse, respectively. When the error ellipse covers the pole, the null hypothesis of no-rhythm (zero amplitude) is accepted (right). Results (P-value from the zero-amplitude test, percentage rhythm or proportion of the overall variance accounted for by the fitted model, MESOR ± SE, amplitude and 95% confidence limits, acrophase and 95% confidence limits) are listed in each case.

So, my question is, can be the polar plot in GLMMcosinor interpreter as the same way as is described in the article when I include a binary predictor? I mean, if I have the model y=X+amp_acro(time,  group = "X", period = 24), then, the polar plot has two ellipse confidential regions. If one of them cover the pole, can I say "the null hypothesis of no-rhythm (zero amplitude) is accepted", meaning the zero-amplitude (no-rhythm) test is not rejected. This suggests the null hypothesis of no rhythm (zero amplitude) cannot be ruled out, indicating a less defined rhythm?????

Best,

Mila

**Comment by RWParsons** [comment]
Hi Mila,

Yes - you're right. These polar plots are made in the same way as described by Cornelissen in that text. It's worth noting that this assessment of rhythmicity is the same as if you assessed whether the amplitude is different from zero (which you can get from the 95% confidence interval on the transformed coefficients when using `summary(model)`.  

There are many tools and models to assess for rhythmicity out there, though. You're right that this is equivalent to the one described in that paper and this has the benefit that you can specify other parts of the model which may be relevant to absorbing variance away from the cosinor component of the data, but it requires you directly specify the period which may not always be known for certain.  If I were using this to assess the presence of rhythmicity I would be wanting to do visual assessments of data to the model fit as well (autoplot() with the data superimposed etc.).  I don't know all the other methods for rhythmicity detection out there but they may have other techniques to account for these other factors.

Cheers,
Rex
