### ISSUE TITLE
autoplot is not in correspondence with mesor in model including covariates

### ISSUE THREAD

**Issue by MilaSMayor** [ropensci/GLMMcosinor#30]
Dear Rex,

Doing this model:
`cglmm(Age+bmi+P1+P2+amp_acro(hour, group = 'P2', period=24)+(1|new_ID), REML=TRUE, data=d)`
I got the mesor using emmeans as you recommended me before. 
The problem lies when doing the autoplot. 
Autoplot is not in correspondence with MESOR in model including covariates.
I gave you a simulated data before. In case you need a data and if it is possible, can I send you a data privately, by email for example? 

Best,

Mila

**Comment by RWParsons** [comment]
Yeah I'd appreciate a complete reprex including the data import/wrangling before fitting the model. My email is the in the `DESCRIPTION` file.

**Comment by RWParsons** [comment]
Hi @MilaSMayor
I've made a small change but also given a bigger description of what's going on with the plot and what to do in this PR: https://github.com/ropensci/GLMMcosinor/pull/31
