### ISSUE TITLE
[Plot legend fix] Make labels more concise and consistent 

### ISSUE THREAD

**Issue by oliverjayasinghe** [ropensci/GLMMcosinor#8]
Plots generated from autoplot() and polar_plot() have inconsistent labelling approaches. This will be addressed and the labels themselves will be more concise where possible.

**Comment by RWParsons** [comment]
while we are editing the labelling of the plots, could you also please prevent the "component [n]" titles displaying when the model has only one component?

```
data(vitamind)
object <- cglmm(
    vit_d ~ amp_acro(time,
                     group = "X",
                     period = 12
    ),
    data = vitamind
)
polar_plot(object)
```
![image](https://github.com/ropensci/GLMMcosinor/assets/47549264/42e808fe-c14a-4b3c-ad20-0c4e892c7183)

**Comment by RWParsons** [comment]
Closed with https://github.com/ropensci/GLMMcosinor/pull/11#issue-2131318269
